runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: 123
  CLOUD_SQL_DATABASE_NAME: epgWebPageDB
  CLOUD_SQL_CONNECTION_NAME: glassy-totality-365703:us-central1:formdb